language: node_js
node_js:
  - v6
  - v5
  - v4
  - '0.12'
  - '0.10'
cache:
  directories:
    - node_modules
install:
  - npm install
  - npm install -g codecov
script:
  - npm run test
  - codecov
after_success:
  - bash <(curl -s https://codecov.io/bash)
